### ISSUE TITLE
Curaçao channel plan should be AS923-1

### ISSUE THREAD

**Issue by gradoj** [gradoj/hplans#2]
Netherlands uses EU868 but Curaçao is AS923-1 in the semtech regional parameters
![image](https://user-images.githubusercontent.com/7544765/109604306-85bdbf00-7ae0-11eb-9aae-463850fc7d16.png)

**Comment by JayKickliter** [comment]
I would have expected Curaçao to use EU868. I wonder who's correct (maybe no one at this point).

**Comment by englotk** [comment]
I totally forgot I set this trap for myself. I incorrectly left Curacao as EU868 as the semtech regional parameters is AS923-1. It sounds like guys on the ground are using US915 currently.  Nothing is working in Curacao since pocv11 was turned on today. 

Going with the semtech regional parameters I'm going to change Curacoa to AS923-1.

**Comment by gradoj** [comment]
I totally forgot I set this trap for myself. I incorrectly left Curacao as EU868 - the semtech regional parameters has it as AS923-1. It sounds like guys on the ground are using US915 currently. Nothing is working in Curacao since pocv11 was turned on today.

Going with the semtech regional parameters I'm going to change Curacoa from EU868 to AS923-1.

**Comment by solarminer-cur** [comment]
Thanks Gradoj! Do you know when this will take effect in production?
